---
- hosts: all
  roles:
    - role: common
    - role: node_control_client
    - role: omd_clone_fake_version
  tasks:
  - name: "omd config change"
    shell: "omd config demo change"
    args:
      stdin: |
        PNP4NAGIOS=off
        GRAFANA=on
        NAGFLUX=on
        INFLUXDB=on
  - copy:
      src: "/root/thruk_local.conf"
      dest: "/omd/sites/demo/etc/thruk/thruk_local.conf"
      owner: "demo"
      group: "demo"
  - copy:
      src: "/scenario/objects.cfg"
      dest: "/omd/sites/demo/etc/naemon/conf.d/objects.cfg"
      owner: "demo"
      group: "demo"
  - shell: sed -e "s/###SITE###/{{ lookup('env','PREFIX') }}/g" -i /omd/sites/demo/etc/naemon/conf.d/objects.cfg -i /omd/sites/demo/etc/thruk/thruk_local.conf
  - shell: sed -e "s/-pnp/-perf/g" -i /omd/sites/demo/etc/naemon/conf.d/objects.cfg
  - shell: echo "key_tier2c" > /omd/sites/demo/var/thruk/secret.key
  - file:
      path: /omd/sites/demo/var/thruk/secret.key
      mode: 0600
      owner: demo
      group: demo
  - name: commit changes to git
    shell:
      cmd: git add etc && git commit -m 'omd config'
      chdir: "/omd/sites/demo"
    become: yes
    become_user: "demo"
