services:
  site:
    image: sni/thruk_org
    build:
      context: ./.thruk_org
    command: jekyll serve --trace --watch
    ports:
      - "4000:4000"
    volumes:
      - ./.thruk_org:/srv/jekyll
      - ../:/srv/jekyll/_submodules/thruk/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000/ || exit 1
      interval: 5s
      retries: 5
      start_period: 120s
      timeout: 10s
